#!/bin/bash

find $1 -name "*.dcm" -exec python ../dicom_attribute_scraper/attribute_scraper.py '{}' -o "{}_scraped" \;

find $1 -name "*.dcm_scraped" -exec python ../dicom_attribute_scraper/aggregator.py '{}' \+

find $1 -name "*.dcm_scraped" -exec rm '{}' \;

